name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        run: dotnet restore

      # Format the output of dotnet format
      - name: Add dotnet-format problem matcher
        uses: xt0rted/dotnet-format-problem-matcher@v1

      # Install dotnet format as a global tool
      - name: Install dotnet format
        run: |
          dotnet tool install --global dotnet-format
          dotnet format --verify-no-changes --verbosity diagnostic

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --filter "FullyQualifiedName~Notion.UnitTests" --no-build --verbosity normal
