name: Test Publish Code

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Person to greet'
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}

      - name: Install dependencies
        run: |
          dotnet restore

      - name: Build solution [Release]
        run: dotnet build --no-restore -c Release

      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal

      - name: Pack solution [Release]
        run: |
          dotnet pack --no-restore --no-build -o PackOutputs -c Release -p:Version=${{ github.event.inputs.version }} -p:PackageReleaseNotes="See https://github.com/notion-dotnet/notion-sdk-net/releases/tag/${{ github.event.inputs.version }}" -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
          rm -f PackOutputs/*.nupkg
          dotnet pack --no-restore --no-build -o PackOutputs -c Release -p:Version=${{ github.event.inputs.version }} -p:PackageReleaseNotes="See https://github.com/notion-dotnet/notion-sdk-net/releases/tag/${{ github.event.inputs.version }}" -p:PackageReadmeFile=README.md

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Notion.Net
          path: PackOutputs/*
